### PR TITLE
Fix issue with non-integer x-descriptors in srcset

### LINKED ISSUE #3852: No images in wikipedia articles
### Issue details

All wikipedia articles are displayed without images. Tested with Firefox, Chrome and Edge.
This is also reproducable with a test account on app.wallabag.it.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.6
* How did you install wallabag? Via `git clone` or by downloading the package? Downloading package
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7.2
* OS: Ubuntu 16.04LTS
* type of hosting (shared or dedicated): shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

### Steps to reproduce/test case

* Set Firefox to normal zoom (display at 100%)
* Add any wikipedia article to wallabag (e.g. https://de.wikipedia.org/wiki/L%C3%B6tkolben, storing images local makes no difference)
* Display the article and Zoom in and out. Images are only displayed if your zoom factor is >100%

Generated source looks like this:
`<div class="thumb tright"><div class="thumbinner"><a href="https://de.wikipedia.org/wiki/Datei:Benzinlötlampen_und_Lötkolben.jpg" class="image"></a>  <div class="thumbcaption">Lötkolben, die mit Lötlampen erhitzt werden</div></div></div>`

If i remove the "1.5x, " from srcset the images are displayed all the time

### PR DESCRIPTION
**Pull request by Kdecherf**
Example:
  `srcset="//example.com/a.jpg 1.5x, //example.com/b.jpg 2x"` resulted in
  `srcset="1.5x, //example.com/b.jpg 2x"`

Fixes https://github.com/wallabag/wallabag/issues/3852

### CODE REVIEW

File: htmLawed.php [hunk 1]
```diff
@@ -519,7 +519,7 @@ function hl_tag($t){
    $v = str_replace("­", ' ', (strpos($v, '&') !== false ? str_replace(array('&#xad;', '&#173;', '&shy;'), ' ', $v) : $v)); # double-quoted char: soft-hyphen; appears here as "­" or hyphen or something else depending on viewing software
    if($k == 'srcset'){
     $v2 = '';
-    $pattern = "/(?:[^\"'\s]+\s*(?:\d+[wx])+)/";
+    $pattern = "/(?:[^\"'\s]+\s*(?:\d+(?:\.\d+)?[wx])+)/";
```
Comment (jtojnar) [inline htmLawed.php]: According to [spec](https://html.spec.whatwg.org/multipage/images.html#srcset-attribute), we might want `\d+w|\d+(?:\.\d+)?x` but maybe this simple regex will do.

Comment (Kdecherf) [reply htmLawed.php]: That's a good point, fixed. Thanks

**Review by jtojnar — APPROVED** [review]
LGTM.

**Review by j0k3r — APPROVED** [review]
